import type { Pet } from "@/features/pets/types";

/** Datos dummy de mascotas (perros y gatos) hasta conectar el backend. */
export const dummyPets: Pet[] = [
  {
    id: "1",
    name: "Truffa",
    species: "dog",
    breed: "Beagle",
    sex: "female",
    ageYears: 4,
    ageMonths: 3,
    birthDate: "21/03/2022",
    weightKg: 11.2,
    nextEvent: { icon: "shield", label: "Antipulgas mensual", date: "21 jun 2026" },
  },
  {
    id: "2",
    name: "Mishi",
    species: "cat",
    breed: "Siamés",
    sex: "female",
    ageYears: 4,
    ageMonths: 11,
    birthDate: "26/07/2021",
    weightKg: 4.1,
    nextEvent: { icon: "gift", label: "¡Cumple de Mishi!", date: "26 jun 2026" },
  },
  {
    id: "3",
    name: "Rocco",
    species: "dog",
    breed: "Mestizo",
    sex: "male",
    ageYears: 6,
    ageMonths: 6,
    birthDate: "17/12/2019",
    weightKg: 23.5,
    nextEvent: { icon: "activity", label: "Séxtuple", date: "17 jun 2026" },
  },
  {
    id: "4",
    name: "Nina",
    species: "cat",
    breed: "Persa",
    sex: "female",
    ageYears: 2,
    ageMonths: 1,
    birthDate: "05/05/2024",
    weightKg: 3.6,
    nextEvent: { icon: "scissors", label: "Peluquería", date: "02 jul 2026" },
  },
  {
    id: "5",
    name: "Thor",
    species: "dog",
    breed: "Golden Retriever",
    sex: "male",
    ageYears: 1,
    ageMonths: 8,
    birthDate: "10/10/2024",
    weightKg: 28.0,
    nextEvent: { icon: "activity", label: "Refuerzo anual", date: "10 ago 2026" },
  },
  {
    id: "6",
    name: "Luna",
    species: "cat",
    breed: "Mestizo",
    sex: "female",
    ageYears: 3,
    ageMonths: 4,
    birthDate: "14/02/2023",
    weightKg: 4.8,
  },
];
